---
- name: Add NTP Server
  ios_config:
    lines: ntp server {{ ntp_ip }}
  when: input_state == 'add'

- name: Remove NTP Server
  ios_config:
    lines: no ntp server {{ ntp_ip }}
  when: input_state == 'remove'
