---
- name: Backup current config
  ios_config:
    backup: yes
  register: backup_config

- debug:
    var: backup_config.backup_path
    verbosity: 3

- block:
    - name: Add VLAN
      ios_config:
        lines: interface vlan{{ vlan_port }}
      when: input_state == 'add'

    - name: Remove VLAN
      ios_config:
        lines: no vlan{{ vlan_port }}
      when: input_state == 'remove'

  rescue:
    - debug:
        var: backup_config.backup_path
        verbosity: 3

    - name: Reset to backed-up config
      ios_config:
        src: "{{ backup_config.backup_path }}"
        save: yes
