---
- name: Add VLAN
  ios_config:
    lines: interface vlan{{ vlan_port }}
  when: input_state == 'add'

- name: Remove VLAN
  ios_config:
    lines: no vlan{{ vlan_port }}
  when: input_state == 'remove'
