---
- name: show version
  ios_command:
    commands: show version
    wait_for: result[0] contains IOS

- name: run multiple commands and evaluate the output
  ios_command:
    commands: show interfaces